-- 코드를 입력하세요
SELECT O.USER_ID, O.PRODUCT_ID
FROM ONLINE_SALE AS O ,ONLINE_SALE AS S
WHERE O.USER_ID = S.USER_ID AND O.PRODUCT_ID = S.PRODUCT_ID AND O.SALES_DATE != S.SALES_DATE
GROUP BY O.USER_ID, O.PRODUCT_ID
ORDER BY O.USER_ID, O.PRODUCT_ID DESC;

